# Generated by Django 4.1.7 on 2023-05-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_app', '0008_remove_courseinfo_user_courseinfo_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='creater',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
