# Generated by Django 4.1.7 on 2023-05-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ed_app', '0010_alter_courseinfo_creater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='creater',
        ),
    ]
